package lk.apluskids.platform.advertisement;
import java.io.*; import java.nio.file.*; import java.util.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Component; import org.springframework.web.multipart.MultipartFile; import lk.apluskids.platform.common.error.ApiException;
@Component class AdvertisementStorage {
 private static final long IMAGE_MAX=20L*1024*1024,VIDEO_MAX=150L*1024*1024; private static final Map<String,String> EXTENSIONS=Map.of("image/jpeg",".jpg","image/png",".png","image/webp",".webp","image/gif",".gif","video/mp4",".mp4","video/webm",".webm"); private final Path root;
 AdvertisementStorage(@Value("${aplus.advertisements.storage-path:./data/advertisements}")String value){root=Paths.get(value).toAbsolutePath().normalize();}
 Stored store(MultipartFile file){if(file==null||file.isEmpty())throw bad("AD_MEDIA_REQUIRED","Choose an advertisement image, GIF or video.");String type=Optional.ofNullable(file.getContentType()).orElse("").toLowerCase(Locale.ROOT);if(!EXTENSIONS.containsKey(type))throw bad("AD_MEDIA_TYPE_INVALID","Use JPG, PNG, WebP, GIF, MP4 or WebM media.");long maximum=type.startsWith("video/")?VIDEO_MAX:IMAGE_MAX;if(file.getSize()>maximum)throw bad("AD_MEDIA_TOO_LARGE",type.startsWith("video/")?"Videos must be 150 MB or smaller.":"Images and GIFs must be 20 MB or smaller.");Path target=null;try{byte[] header=new byte[16];try(InputStream in=file.getInputStream()){int read=in.read(header);if(read<4||!validSignature(type,header,read))throw bad("AD_MEDIA_INVALID","The selected file content does not match its media type.");}Files.createDirectories(root);String name=UUID.randomUUID()+EXTENSIONS.get(type);target=root.resolve(name).normalize();if(!root.equals(target.getParent()))throw new IOException("Invalid path");try(InputStream in=file.getInputStream()){Files.copy(in,target,StandardCopyOption.REPLACE_EXISTING);}return new Stored(name,safeName(file.getOriginalFilename()),type,file.getSize());}catch(ApiException e){deletePath(target);throw e;}catch(IOException e){deletePath(target);throw new ApiException(HttpStatus.INTERNAL_SERVER_ERROR,"AD_MEDIA_STORAGE_FAILED","The advertisement media could not be saved.");}}
 Path get(String name){if(name==null||name.isBlank())throw new ApiException(HttpStatus.NOT_FOUND,"AD_MEDIA_NOT_FOUND","Advertisement media is unavailable.");Path value=root.resolve(name).normalize();if(!root.equals(value.getParent())||!Files.isRegularFile(value))throw new ApiException(HttpStatus.NOT_FOUND,"AD_MEDIA_NOT_FOUND","Advertisement media is unavailable.");return value;} void delete(String name){if(name!=null)deletePath(root.resolve(name).normalize());} private void deletePath(Path value){if(value==null||!root.equals(value.getParent()))return;try{Files.deleteIfExists(value);}catch(IOException ignored){}}
 private static boolean validSignature(String type,byte[] h,int n){if(type.equals("image/jpeg"))return n>=3&&(h[0]&255)==255&&(h[1]&255)==216&&(h[2]&255)==255;if(type.equals("image/png"))return n>=8&&(h[0]&255)==137&&h[1]==80&&h[2]==78&&h[3]==71&&h[4]==13&&h[5]==10&&h[6]==26&&h[7]==10;if(type.equals("image/gif"))return n>=6&&new String(h,0,6,java.nio.charset.StandardCharsets.US_ASCII).matches("GIF8[79]a");if(type.equals("image/webp"))return n>=12&&new String(h,0,4,java.nio.charset.StandardCharsets.US_ASCII).equals("RIFF")&&new String(h,8,4,java.nio.charset.StandardCharsets.US_ASCII).equals("WEBP");if(type.equals("video/mp4"))return n>=12&&new String(h,4,4,java.nio.charset.StandardCharsets.US_ASCII).equals("ftyp");return type.equals("video/webm")&&n>=4&&(h[0]&255)==26&&(h[1]&255)==69&&(h[2]&255)==223&&(h[3]&255)==163;} private static String safeName(String value){if(value==null)return "advertisement";String name=Paths.get(value).getFileName().toString().replaceAll("[^A-Za-z0-9._ -]","_");return name.length()>180?name.substring(name.length()-180):name;} private static ApiException bad(String code,String message){return new ApiException(HttpStatus.BAD_REQUEST,code,message);} record Stored(String name,String originalName,String mediaType,long size){}
}
