package lk.apluskids.platform.advertisement;
import java.net.URI; import java.nio.file.Path; import java.time.*; import java.util.*; import org.springframework.http.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile; import lk.apluskids.platform.common.error.ApiException; import lk.apluskids.platform.user.*;
@Service public class AdvertisementService {
 public static final Set<String> SLOTS=Set.of("HOME_AFTER_HERO","HOME_AFTER_SHORTCUTS","HOME_BEFORE_SCHEDULE","KIDS_ZONE_AFTER_HERO","WATCH_BEFORE_CATEGORIES","MARKET_PROMO_BANNER"); private static final Set<String> TYPES=Set.of("IMAGE","GIF","VIDEO","CARD","EMBED"),FITS=Set.of("CONTAIN","COVER"); private static final ZoneId ZONE=ZoneId.of("Asia/Colombo");
 private final AdvertisementRepository ads; private final AdvertisementPlacementRepository placements; private final AdvertisementAuditRepository audits; private final AdvertisementStorage storage; private final UserRepository users; private final JdbcTemplate jdbc;
 AdvertisementService(AdvertisementRepository a,AdvertisementPlacementRepository p,AdvertisementAuditRepository h,AdvertisementStorage s,UserRepository u,JdbcTemplate j){ads=a;placements=p;audits=h;storage=s;users=u;jdbc=j;}
 @Transactional(readOnly=true) public List<AdvertisementView> list(){return ads.findAllByOrderByCreatedAtDesc().stream().map(this::view).toList();}
 @Transactional(readOnly=true) public List<PublicAdvertisement> active(String slot){return ads.active(slot(slot),Instant.now()).stream().map(this::publicView).toList();}
 @Transactional public AdvertisementView create(UUID actor,AdvertisementRequest request){UserEntity user=user(actor);AdvertisementEntity ad=new AdvertisementEntity();apply(ad,request);ad.createdBy(user);ad.updatedBy(user);ads.save(ad);slots(ad,request.slots());audit(ad,user,"ADVERTISEMENT_CREATED","Advertisement draft created.");return view(ad);}
 @Transactional public AdvertisementView update(UUID actor,UUID id,AdvertisementRequest request){AdvertisementEntity ad=ad(id);apply(ad,request);UserEntity user=user(actor);ad.updatedBy(user);slots(ad,request.slots());audit(ad,user,"ADVERTISEMENT_UPDATED","Advertisement details changed.");return view(ad);}
 @Transactional public AdvertisementView upload(UUID actor,UUID id,String variant,MultipartFile file){if(!Set.of("desktop","mobile").contains(variant))throw bad("AD_VARIANT_INVALID","Choose desktop or mobile media.");AdvertisementEntity ad=ad(id);AdvertisementStorage.Stored stored=storage.store(file);String old="desktop".equals(variant)?ad.desktopFilename():ad.mobileFilename();if("desktop".equals(variant))ad.desktop(stored.name(),stored.originalName(),stored.mediaType());else ad.mobile(stored.name(),stored.originalName(),stored.mediaType());ad.updatedBy(user(actor));if(old!=null)storage.delete(old);audit(ad,user(actor),"ADVERTISEMENT_MEDIA_UPDATED",variant+" media uploaded.");return view(ad);}
 @Transactional public AdvertisementView status(UUID actor,UUID id,String next){AdvertisementEntity ad=ad(id);String value=upper(next,"");if(!Set.of("ACTIVE","PAUSED","ARCHIVED","DRAFT").contains(value))throw bad("AD_STATUS_INVALID","Choose a valid advertisement status.");if("ACTIVE".equals(value))publishable(ad);ad.status(value);ad.updatedBy(user(actor));audit(ad,user(actor),"ADVERTISEMENT_"+value,"Advertisement status changed to "+value+".");return view(ad);}
 @Transactional public void delete(UUID actor,UUID id){AdvertisementEntity ad=ad(id);if("ACTIVE".equals(ad.status()))throw new ApiException(HttpStatus.CONFLICT,"AD_DELETE_ACTIVE","Pause or archive this advertisement before deleting it.");String desktop=ad.desktopFilename(),mobile=ad.mobileFilename();audit(ad,user(actor),"ADVERTISEMENT_DELETED","Advertisement permanently deleted.");audits.flush();ads.delete(ad);storage.delete(desktop);storage.delete(mobile);}
 @Transactional public void impression(UUID id){if(ads.impression(id)>0)metric(id,1,0);}
 @Transactional public URI click(UUID id){AdvertisementEntity ad=ad(id);if(ad.destinationUrl()==null||ad.destinationUrl().isBlank())throw new ApiException(HttpStatus.NOT_FOUND,"AD_LINK_NOT_FOUND","This advertisement has no destination link.");ads.click(id);metric(id,0,1);return URI.create(ad.destinationUrl());}
 @Transactional(readOnly=true) public Asset asset(UUID id,String variant){AdvertisementEntity ad=ad(id);boolean mobile="mobile".equals(variant)&&ad.mobileFilename()!=null;return new Asset(storage.get(mobile?ad.mobileFilename():ad.desktopFilename()),mobile?ad.mobileMediaType():ad.desktopMediaType());}
 private void metric(UUID id,long impressions,long clicks){jdbc.update("insert into advertisement_daily_metrics(advertisement_id,metric_date,impressions,clicks) select id,?,?,? from advertisements where public_id=? on conflict(advertisement_id,metric_date) do update set impressions=advertisement_daily_metrics.impressions+excluded.impressions,clicks=advertisement_daily_metrics.clicks+excluded.clicks,updated_at=now()",LocalDate.now(ZONE),impressions,clicks,id);}
 private void apply(AdvertisementEntity ad,AdvertisementRequest r){String name=required(r.name(),160,"Advertisement name is required."),type=upper(r.contentType(),"IMAGE"),fit=upper(r.fitMode(),"CONTAIN");if(!TYPES.contains(type))throw bad("AD_TYPE_INVALID","Choose image, GIF, video, card or embed.");if(!FITS.contains(fit))throw bad("AD_FIT_INVALID","Choose Contain or Cover.");if(r.endsAt()!=null&&r.startsAt()!=null&&!r.endsAt().isAfter(r.startsAt()))throw bad("AD_SCHEDULE_INVALID","The end time must be after the start time.");String destination=url(r.destinationUrl(),true),external=url(r.externalSourceUrl(),false);if("EMBED".equals(type)&&(external==null||!embed(external)))throw bad("AD_EMBED_INVALID","Use an approved YouTube or Vimeo embed link.");String background=r.backgroundColor()==null?"#FFFFFF":r.backgroundColor().trim();if(!background.matches("^#[0-9A-Fa-f]{6}$"))throw bad("AD_BACKGROUND_INVALID","Use a six-digit hexadecimal background colour.");ad.metadata(name,type,trim(r.title(),180),trim(r.description(),2000),trim(r.buttonLabel(),80),trim(r.altText(),300),destination,r.openNewTab(),fit,background,r.startsAt(),r.endsAt(),r.priority(),Math.max(1,Math.min(100,r.rotationWeight())),external);}
 private void publishable(AdvertisementEntity ad){if(placements.findAllByAdvertisement(ad).isEmpty())throw bad("AD_SLOT_REQUIRED","Choose at least one page placement before publishing.");if(Set.of("IMAGE","GIF","VIDEO").contains(ad.contentType())&&ad.desktopFilename()==null)throw bad("AD_MEDIA_REQUIRED","Upload desktop media before publishing.");if("CARD".equals(ad.contentType())&&(ad.title()==null||ad.title().isBlank()))throw bad("AD_CARD_TITLE_REQUIRED","Add a title before publishing this card.");}
 private void slots(AdvertisementEntity ad,List<String> items){placements.deleteAllByAdvertisement(ad);placements.flush();if(items!=null)items.stream().map(this::slot).distinct().forEach(item->placements.save(new AdvertisementPlacementEntity(ad,item)));}
 private AdvertisementView view(AdvertisementEntity ad){return new AdvertisementView(ad.publicId(),ad.name(),ad.contentType(),ad.status(),lifecycle(ad),ad.title(),ad.destinationUrl(),ad.desktopFilename()!=null,ad.mobileFilename()!=null,ad.externalSourceUrl(),ad.startsAt(),ad.endsAt(),ad.priority(),ad.rotationWeight(),ad.impressionCount(),ad.clickCount(),placements.findAllByAdvertisement(ad).stream().map(AdvertisementPlacementEntity::slotKey).sorted().toList());}
 private PublicAdvertisement publicView(AdvertisementEntity ad){return new PublicAdvertisement(ad.publicId(),ad.contentType(),ad.title(),ad.destinationUrl()==null?null:"/api/v1/advertisements/"+ad.publicId()+"/redirect",ad.openNewTab(),ad.fitMode(),ad.backgroundColor(),ad.desktopFilename()==null?ad.externalSourceUrl():"/api/v1/advertisements/"+ad.publicId()+"/assets/desktop",ad.mobileFilename()==null?null:"/api/v1/advertisements/"+ad.publicId()+"/assets/mobile",ad.rotationWeight());}
 private String lifecycle(AdvertisementEntity ad){Instant now=Instant.now();if("ACTIVE".equals(ad.status())&&ad.startsAt()!=null&&ad.startsAt().isAfter(now))return "SCHEDULED";if("ACTIVE".equals(ad.status())&&ad.endsAt()!=null&&!ad.endsAt().isAfter(now))return "EXPIRED";return ad.status();}
 private AdvertisementEntity ad(UUID id){return ads.findByPublicId(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"ADVERTISEMENT_NOT_FOUND","Advertisement not found."));} private UserEntity user(UUID id){return users.findByPublicId(id).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"ADMIN_NOT_FOUND","Administrator access could not be verified."));} private void audit(AdvertisementEntity ad,UserEntity actor,String action,String details){AdvertisementAuditEntity item=new AdvertisementAuditEntity();item.values(ad,actor,action,details);audits.save(item);} private String slot(String value){value=upper(value,"");if(!SLOTS.contains(value))throw bad("AD_SLOT_INVALID","Choose an available advertisement placement.");return value;}
 private static String url(String value,boolean internal){if(value==null||value.isBlank())return null;value=value.trim();if(internal&&value.startsWith("/")&&!value.startsWith("//"))return value;if(value.matches("(?i)^[\\w-]+(?:\\.[\\w-]+)+(?:[/?#].*)?$"))value="https://"+value;try{URI uri=URI.create(value);if(!Set.of("http","https").contains(Optional.ofNullable(uri.getScheme()).orElse("").toLowerCase(Locale.ROOT))||uri.getHost()==null)throw new IllegalArgumentException();return value;}catch(IllegalArgumentException e){throw bad("AD_URL_INVALID","Use a valid HTTP, HTTPS or internal website link.");}} private static boolean embed(String value){String host=URI.create(value).getHost().toLowerCase(Locale.ROOT);return host.equals("youtu.be")||host.endsWith("youtube.com")||host.equals("vimeo.com")||host.endsWith("vimeo.com");} private static String required(String value,int max,String message){value=trim(value,max);if(value==null)throw bad("AD_NAME_REQUIRED",message);return value;} private static String trim(String value,int max){if(value==null)return null;value=value.trim();return value.isBlank()?null:value.substring(0,Math.min(max,value.length()));} private static String upper(String value,String fallback){return value==null||value.isBlank()?fallback:value.trim().toUpperCase(Locale.ROOT);} private static ApiException bad(String code,String message){return new ApiException(HttpStatus.BAD_REQUEST,code,message);}
 public record AdvertisementRequest(String name,String contentType,String title,String description,String buttonLabel,String altText,String destinationUrl,boolean openNewTab,String fitMode,String backgroundColor,String externalSourceUrl,Instant startsAt,Instant endsAt,int priority,int rotationWeight,List<String> slots){} public record AdvertisementView(UUID id,String name,String contentType,String status,String lifecycle,String title,String destinationUrl,boolean desktopMedia,boolean mobileMedia,String externalSourceUrl,Instant startsAt,Instant endsAt,int priority,int rotationWeight,long impressions,long clicks,List<String> slots){} public record PublicAdvertisement(UUID id,String contentType,String title,String destinationUrl,boolean openNewTab,String fitMode,String backgroundColor,String desktopSource,String mobileSource,int rotationWeight){} public record Asset(Path path,String mediaType){}
}
