package lk.apluskids.platform.advertisement;

import java.net.URI;
import java.nio.file.Path;
import java.time.*;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.*;
import org.springframework.transaction.support.*;
import org.springframework.web.multipart.MultipartFile;
import lk.apluskids.platform.common.error.ApiException;
import lk.apluskids.platform.user.*;

@Service
public class AdvertisementService {
    public static final Set<String> SLOTS=Set.of("HOME_AFTER_HERO","HOME_AFTER_SHORTCUTS","HOME_BEFORE_SCHEDULE","KIDS_ZONE_AFTER_HERO","WATCH_BEFORE_CATEGORIES","MARKET_PROMO_BANNER");
    private static final Set<String> TYPES=Set.of("IMAGE","GIF","VIDEO","CARD","EMBED"),FITS=Set.of("CONTAIN","COVER");
    private static final ZoneId REPORTING_ZONE=ZoneId.of("Asia/Colombo");
    private final AdvertisementRepository ads;private final AdvertisementPlacementRepository placements;private final AdvertisementAuditRepository audits;private final AdvertisementStorage storage;private final UserRepository users;private final JdbcTemplate jdbc;
    public AdvertisementService(AdvertisementRepository ads,AdvertisementPlacementRepository placements,AdvertisementAuditRepository audits,AdvertisementStorage storage,UserRepository users,JdbcTemplate jdbc){this.ads=ads;this.placements=placements;this.audits=audits;this.storage=storage;this.users=users;this.jdbc=jdbc;}

    @Transactional(readOnly=true) public List<AdvertisementView> list(){return ads.findAllByOrderByCreatedAtDesc().stream().map(this::view).toList();}
    @Transactional(readOnly=true) public List<PublicAdvertisement> active(String slot){slot=slot(slot);return ads.active(slot,Instant.now()).stream().map(this::publicView).toList();}
    @Transactional(readOnly=true) public List<AuditView> history(){return audits.findTop300ByOrderByCreatedAtDesc().stream().map(a->new AuditView(a.advertisementPublicId(),a.action(),a.details(),a.actorName(),a.createdAt())).toList();}
    @Transactional public AdvertisementView create(UUID actor,AdvertisementRequest request){
        var user=user(actor);var ad=new AdvertisementEntity();apply(ad,request);ad.createdBy(user);ad.updatedBy(user);ads.save(ad);replaceSlots(ad,request.slots());audit(ad,user,"ADVERTISEMENT_CREATED","Advertisement draft created.");return view(ad);
    }
    @Transactional public AdvertisementView update(UUID actor,UUID id,AdvertisementRequest request){var ad=ad(id);apply(ad,request);ad.updatedBy(user(actor));replaceSlots(ad,request.slots());audit(ad,user(actor),"ADVERTISEMENT_UPDATED","Advertisement details, destination or schedule changed.");return view(ad);}
    @Transactional public AdvertisementView upload(UUID actor,UUID id,String variant,MultipartFile file){
        var ad=ad(id);if(!Set.of("desktop","mobile").contains(variant))throw bad("AD_VARIANT_INVALID","Choose the desktop or mobile media slot.");var stored=storage.store(file);String old="desktop".equals(variant)?ad.desktopFilename():ad.mobileFilename();
        if("desktop".equals(variant))ad.desktop(stored.name(),stored.originalName(),stored.mediaType());else ad.mobile(stored.name(),stored.originalName(),stored.mediaType());ad.updatedBy(user(actor));
        afterCompletion(status->{if(status!=TransactionSynchronization.STATUS_COMMITTED)storage.delete(stored.name());else storage.delete(old);});audit(ad,user(actor),"ADVERTISEMENT_MEDIA_UPDATED",variant+" media uploaded.");return view(ad);
    }
    @Transactional public AdvertisementView status(UUID actor,UUID id,String value){var ad=ad(id);value=value.toUpperCase(Locale.ROOT);if(!Set.of("ACTIVE","PAUSED","ARCHIVED","DRAFT").contains(value))throw bad("AD_STATUS_INVALID","Choose a valid advertisement status.");if("ACTIVE".equals(value))validatePublish(ad);ad.status(value);ad.updatedBy(user(actor));audit(ad,user(actor),"ADVERTISEMENT_"+value,"Advertisement status changed to "+value+".");return view(ad);}
    @Transactional public void impression(UUID id){if(ads.impression(id)>0)incrementMetric(id,true);}
    @Transactional public URI click(UUID id){var ad=ad(id);if(ad.destinationUrl()==null||ad.destinationUrl().isBlank())throw new ApiException(HttpStatus.NOT_FOUND,"AD_LINK_NOT_FOUND","This advertisement has no destination link.");ads.click(id);incrementMetric(id,false);return URI.create(ad.destinationUrl());}
    @Transactional(readOnly=true) public AnalyticsResponse analytics(UUID id,int requestedDays){int days=Math.max(1,Math.min(730,requestedDays));LocalDate to=LocalDate.now(REPORTING_ZONE);return analytics(id,to.minusDays(days-1L),to);}
    @Transactional(readOnly=true) public AnalyticsResponse analytics(UUID id,LocalDate from,LocalDate to){LocalDate today=LocalDate.now(REPORTING_ZONE);if(from==null||to==null||from.isAfter(to)||to.isAfter(today))throw bad("AD_ANALYTICS_RANGE_INVALID","Choose a valid reporting period ending today or earlier.");long requestedDays=java.time.temporal.ChronoUnit.DAYS.between(from,to)+1;if(requestedDays>730)throw bad("AD_ANALYTICS_RANGE_TOO_LARGE","Choose a reporting period of 730 days or fewer.");int days=Math.toIntExact(requestedDays);List<AdvertisementEntity> values=id==null?ads.findAllByOrderByCreatedAtDesc():List.of(ad(id));Map<UUID,AnalyticsBuilder> series=new LinkedHashMap<>();for(var value:values)series.put(value.publicId(),new AnalyticsBuilder(value,from,to));jdbc.query("select public_id,impression_count,click_count from advertisements",result->{var item=series.get(result.getObject("public_id",UUID.class));if(item!=null)item.totals(result.getLong("impression_count"),result.getLong("click_count"));});jdbc.query("select a.public_id,m.metric_date,m.impressions,m.clicks from advertisement_daily_metrics m join advertisements a on a.id=m.advertisement_id where m.metric_date between ? and ? order by m.metric_date",result->{UUID publicId=result.getObject("public_id",UUID.class);var item=series.get(publicId);if(item!=null)item.put(result.getObject("metric_date",LocalDate.class),result.getLong("impressions"),result.getLong("clicks"));},from,to);return new AnalyticsResponse(from,to,days,series.values().stream().map(AnalyticsBuilder::view).toList());}
    @Transactional public void delete(UUID actor,UUID id){var ad=ad(id);if("ACTIVE".equals(ad.status()))throw new ApiException(HttpStatus.CONFLICT,"AD_DELETE_ACTIVE","Archive or pause this advertisement before deleting it.");var admin=user(actor);String desktop=ad.desktopFilename(),mobile=ad.mobileFilename(),name=ad.name();audit(ad,admin,"ADVERTISEMENT_DELETED","Advertisement '"+name+"' was permanently deleted.");audits.flush();if(ads.deletePermanent(id)!=1)throw new ApiException(HttpStatus.NOT_FOUND,"ADVERTISEMENT_NOT_FOUND","The advertisement could not be found.");afterCompletion(status->{if(status==TransactionSynchronization.STATUS_COMMITTED){storage.delete(desktop);storage.delete(mobile);}});}
    @Transactional(readOnly=true) public Asset asset(UUID id,String variant){var ad=ad(id);String file="mobile".equals(variant)&&ad.mobileFilename()!=null?ad.mobileFilename():ad.desktopFilename();String type="mobile".equals(variant)&&ad.mobileFilename()!=null?ad.mobileMediaType():ad.desktopMediaType();return new Asset(storage.get(file),type==null?"application/octet-stream":type);}

    private void apply(AdvertisementEntity ad,AdvertisementRequest r){
        String name=clean(r.name(),160,"Advertisement name is required."),type=upper(r.contentType(),"IMAGE"),fit=upper(r.fitMode(),"CONTAIN");if(!TYPES.contains(type))throw bad("AD_TYPE_INVALID","Choose image, GIF, video, card or approved embed content.");if(!FITS.contains(fit))throw bad("AD_FIT_INVALID","Choose Contain or Cover.");
        if(r.endsAt()!=null&&r.startsAt()!=null&&!r.endsAt().isAfter(r.startsAt()))throw bad("AD_SCHEDULE_INVALID","The end time must be after the start time.");String destination=url(r.destinationUrl(),true);String external=url(r.externalSourceUrl(),false);if("EMBED".equals(type)&&external!=null&&!approvedEmbed(external))throw bad("AD_EMBED_INVALID","Only approved YouTube or Vimeo embed links are supported.");
        String bg=r.backgroundColor()==null?"#FFFFFF":r.backgroundColor().trim();if(!bg.matches("^#[0-9A-Fa-f]{6}$"))throw bad("AD_BACKGROUND_INVALID","Use a six-digit hexadecimal background colour.");ad.metadata(name,type,trim(r.title(),180),trim(r.description(),2000),trim(r.buttonLabel(),80),trim(r.altText(),300),destination,r.openNewTab(),fit,bg,r.startsAt(),r.endsAt(),r.priority(),Math.max(1,Math.min(100,r.rotationWeight())),external);
    }
    private void validatePublish(AdvertisementEntity ad){if(placements.findAllByAdvertisement(ad).isEmpty())throw bad("AD_SLOT_REQUIRED","Assign at least one page placement before publishing.");if(Set.of("IMAGE","GIF","VIDEO").contains(ad.contentType())&&ad.desktopFilename()==null&&ad.externalSourceUrl()==null)throw bad("AD_MEDIA_REQUIRED","Upload desktop media before publishing.");if("CARD".equals(ad.contentType())&&(ad.title()==null||ad.title().isBlank()))throw bad("AD_CARD_TITLE_REQUIRED","Add a title before publishing this promotional card.");if("EMBED".equals(ad.contentType())&&ad.externalSourceUrl()==null)throw bad("AD_EMBED_REQUIRED","Add an approved embed link before publishing.");}
    private void replaceSlots(AdvertisementEntity ad,List<String> values){placements.deleteAllByAdvertisement(ad);placements.flush();if(values==null)return;values.stream().map(this::slot).distinct().forEach(value->placements.save(new AdvertisementPlacementEntity(ad,value)));}
    private AdvertisementView view(AdvertisementEntity ad){List<String> slots=placements.findAllByAdvertisement(ad).stream().map(AdvertisementPlacementEntity::slotKey).sorted().toList();String lifecycle=lifecycle(ad);return new AdvertisementView(ad.publicId(),ad.name(),ad.contentType(),ad.status(),lifecycle,ad.title(),ad.description(),ad.buttonLabel(),ad.altText(),ad.destinationUrl(),ad.openNewTab(),ad.fitMode(),ad.backgroundColor(),ad.desktopFilename()!=null,ad.mobileFilename()!=null,ad.externalSourceUrl(),ad.startsAt(),ad.endsAt(),ad.priority(),ad.rotationWeight(),ad.impressionCount(),ad.clickCount(),slots,ad.createdAt(),ad.updatedAt());}
    private PublicAdvertisement publicView(AdvertisementEntity ad){return new PublicAdvertisement(ad.publicId(),ad.contentType(),ad.title(),ad.description(),ad.buttonLabel(),ad.altText(),ad.destinationUrl()==null?null:"/api/v1/advertisements/"+ad.publicId()+"/redirect",ad.openNewTab(),ad.fitMode(),ad.backgroundColor(),ad.desktopFilename()==null?ad.externalSourceUrl():"/api/v1/advertisements/"+ad.publicId()+"/assets/desktop",ad.mobileFilename()==null?null:"/api/v1/advertisements/"+ad.publicId()+"/assets/mobile",ad.rotationWeight());}
    private String lifecycle(AdvertisementEntity ad){Instant now=Instant.now();if("ACTIVE".equals(ad.status())&&ad.startsAt()!=null&&ad.startsAt().isAfter(now))return "SCHEDULED";if("ACTIVE".equals(ad.status())&&ad.endsAt()!=null&&!ad.endsAt().isAfter(now))return "EXPIRED";return ad.status();}
    private AdvertisementEntity ad(UUID id){return ads.findByPublicId(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"ADVERTISEMENT_NOT_FOUND","The advertisement could not be found."));}private UserEntity user(UUID id){return users.findByPublicId(id).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"ADMIN_NOT_FOUND","Administrator access could not be verified."));}
    private AdvertisementAuditEntity audit(AdvertisementEntity ad,UserEntity actor,String action,String details){var item=new AdvertisementAuditEntity();item.values(ad,actor,action,details);return audits.save(item);}
    private void incrementMetric(UUID id,boolean impression){jdbc.update("insert into advertisement_daily_metrics(advertisement_id,metric_date,impressions,clicks) select id,?,?,? from advertisements where public_id=? on conflict(advertisement_id,metric_date) do update set impressions=advertisement_daily_metrics.impressions+excluded.impressions,clicks=advertisement_daily_metrics.clicks+excluded.clicks,updated_at=now()",LocalDate.now(REPORTING_ZONE),impression?1L:0L,impression?0L:1L,id);}
    private static void afterCompletion(java.util.function.IntConsumer action){if(TransactionSynchronizationManager.isSynchronizationActive())TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization(){@Override public void afterCompletion(int status){action.accept(status);}});}
    private String slot(String value){value=upper(value,"");if(!SLOTS.contains(value))throw bad("AD_SLOT_INVALID","Choose an available advertisement placement.");return value;}
    private static String url(String value,boolean relative){if(value==null||value.isBlank())return null;value=value.trim();if(relative&&value.startsWith("/")&&!value.startsWith("//"))return value;if(value.matches("(?i)^[\\w-]+(?:\\.[\\w-]+)+(?:[/?#].*)?$"))value="https://"+value;try{URI uri=URI.create(value);if(!Set.of("http","https").contains(Optional.ofNullable(uri.getScheme()).orElse("").toLowerCase(Locale.ROOT))||uri.getHost()==null)throw new IllegalArgumentException();return value;}catch(IllegalArgumentException ex){throw bad("AD_URL_INVALID","Use a valid HTTP, HTTPS or internal website link.");}}
    private static boolean approvedEmbed(String value){String host=URI.create(value).getHost().toLowerCase(Locale.ROOT);return host.equals("youtube.com")||host.endsWith(".youtube.com")||host.equals("youtu.be")||host.equals("vimeo.com")||host.endsWith(".vimeo.com");}
    private static String clean(String value,int max,String message){value=trim(value,max);if(value==null||value.isBlank())throw bad("AD_NAME_REQUIRED",message);return value;}private static String trim(String value,int max){if(value==null)return null;value=value.trim();return value.isEmpty()?null:value.substring(0,Math.min(max,value.length()));}private static String upper(String value,String fallback){return value==null||value.isBlank()?fallback:value.trim().toUpperCase(Locale.ROOT);}private static ApiException bad(String code,String message){return new ApiException(HttpStatus.BAD_REQUEST,code,message);}
    public record AdvertisementRequest(String name,String contentType,String title,String description,String buttonLabel,String altText,String destinationUrl,boolean openNewTab,String fitMode,String backgroundColor,String externalSourceUrl,Instant startsAt,Instant endsAt,int priority,int rotationWeight,List<String> slots){}
    public record AdvertisementView(UUID id,String name,String contentType,String status,String lifecycle,String title,String description,String buttonLabel,String altText,String destinationUrl,boolean openNewTab,String fitMode,String backgroundColor,boolean desktopMedia,boolean mobileMedia,String externalSourceUrl,Instant startsAt,Instant endsAt,int priority,int rotationWeight,long impressions,long clicks,List<String> slots,Instant createdAt,Instant updatedAt){}
    public record PublicAdvertisement(UUID id,String contentType,String title,String description,String buttonLabel,String altText,String destinationUrl,boolean openNewTab,String fitMode,String backgroundColor,String desktopSource,String mobileSource,int rotationWeight){}
    public record AuditView(UUID advertisementId,String action,String details,String actor,Instant createdAt){}
    public record DailyMetric(LocalDate date,long impressions,long clicks){}
    public record AnalyticsSeries(UUID advertisementId,String name,long lifetimeImpressions,long lifetimeClicks,List<DailyMetric> points){}
    public record AnalyticsResponse(LocalDate from,LocalDate to,int days,List<AnalyticsSeries> series){}
    public record Asset(Path path,String mediaType){}
    private static final class AnalyticsBuilder{private final AdvertisementEntity ad;private long lifetimeImpressions,lifetimeClicks;private final LinkedHashMap<LocalDate,long[]> points=new LinkedHashMap<>();AnalyticsBuilder(AdvertisementEntity value,LocalDate from,LocalDate to){ad=value;lifetimeImpressions=value.impressionCount();lifetimeClicks=value.clickCount();for(LocalDate day=from;!day.isAfter(to);day=day.plusDays(1))points.put(day,new long[]{0,0});}void totals(long impressions,long clicks){lifetimeImpressions=impressions;lifetimeClicks=clicks;}void put(LocalDate day,long impressions,long clicks){points.put(day,new long[]{impressions,clicks});}AnalyticsSeries view(){return new AnalyticsSeries(ad.publicId(),ad.name(),lifetimeImpressions,lifetimeClicks,points.entrySet().stream().map(entry->new DailyMetric(entry.getKey(),entry.getValue()[0],entry.getValue()[1])).toList());}}
}
