aplus:
  whatsapp:
    graph-api-version: v25.0
    phone-number-id: "1203893376148242"
    business-account-id: "1517033336324166"
    access-token: "EAATu9QNLgcUBSGPkZCWKa9Kq5IDZAt8ZAKHOnHA8l8kNSDO2iVdNn9TVEPBFAJJpOjWF608DghUExAUlnVYowuFRdam409VAZAqqNGmiNcVqQszM99DzHrp2REeqiCVouyneWNKUXkGPfBjaQSlgKwNzAo6ycPU2lGBlalzMW0hLzKCd3GJuAtN1mTReKLNBKZCAnRRwDym9ZBFOjdeLKPen7wZCnvvZAAScXxFf"
